library(shinydashboard)
library(AnnotationDbi)
library(org.Mm.eg.db)
library(EnsDb.Mmusculus.v79)
library(limma)
library(tidyverse)
library(DT)
library(purrr)
library(plotly)
library(chorddiag)
library(DESeq2)
library(fgsea)
library(shinyalert)
source("utils.R")
options(shiny.maxRequestSize = 3000*1024^2)

 ### HEADER ############
header <- dashboardHeader(title = "RNAseq viewer and report App", 
                  titleWidth = 300, 
                  dropdownMenuOutput("messageMenu"),
                  tags$li(class = "dropdown", actionButton("aboutButton", "About"),
                          style="margin-top:8px; margin-right: 5px")
                  )
### SIDEBAR ##########
sidebar <- dashboardSidebar(useShinyalert(),
                            sidebarMenu(
                            menuItem(
                            fileInput("deseqFile",
                                      "Choose RDS with DESeq object",
                                      placeholder = "RDS DESeq"))),
                            sidebarMenu(
                              menuItem("App Information",
                                       tabName = "info",
                                       icon = icon("info")),
                              menuItem("Preview dataset",
                                       tabName = "preview",
                                       icon = icon("eye")),
                              menuItem(
                                "Kegg Enrichment",
                                tabName = "kegg",
                                icon = icon("chart-bar")
                              ),
                              menuItem(
                                "GO Enrichment",
                                tabName = "go",
                                icon = icon("chart-bar")
                              ),
                              menuItem(
                                "GSEA",
                                tabName = "gsea",
                                icon = icon("chart-line")
                              ),
                              sidebarMenu(
                              menuItem(
                              textInput("author", value="your name...", label = h4("Author report name")
                                        ))),
                              sidebarMenu( 
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("report"))))),
                              sidebarMenu(
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("pdf")))))
                            ))
### BODY ###############
body <- dashboardBody(
    shiny::tagList(shiny::tags$head(
        shiny::tags$link(rel = "stylesheet", type = "text/css", href = "busystyle.css"),
        shiny::tags$script(type = "text/javascript", src = "busy.js")
    )),
    div(
        class = "busy",
        h4("Loading data, please be patient..."),
        img(src = "dna.gif"),
        style = "z-index: 99; rgba(236, 240, 245, 0.5)"
    ),
    tabItems(
        # Initial INFO
        tabItem(tabName = "info",
              h1(strong("Welcome to Enrich app 2020!")),
              br(),
              h3("Before starting using the app"),
              p("As a necessary initial element to start the analysis, 
                the program imports an object of the type DeseqDataSet, 
                generated by the DESeq function of the", 
                a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
                "library. It has to be compress as an RDS object and upload 
                by clicking on the search engine button found in the upper left 
                corner of the app. Choose your object and enjoy your enrichment analysis ;)"),
              br(),
              h3("How to download the app"),
              p("This app can be found on ",
                a("GitHub.", 
                  href = "https://github.com/")),
                
        ),
        # preview tab
        tabItem(tabName = "preview",
                fluidRow( 
                  column(width = 2, uiOutput("sampleGroup")),
                  column(width = 2, uiOutput("specie")),
                  column(width = 3, uiOutput("logfc")),
                  column(width = 3, uiOutput("padj")),
                  column(width = 2, strong("Click to compute enrichment"), actionButton("runEnrich", "Apply values"))
                  ) ,
                h3("Samples info (colData)"),
                fluidRow(
                    column(
                        width = 8,
                        offset = 2,
                        dataTableOutput("samples"),
                    )
                ),
                hr(),
                h3("DE results"),
                fluidRow(
                    column(
                        width = 8,
                        offset = 2,
                        DTOutput("preview")
                    )
                ),
                hr(),
                h3("PCA"),
                fluidRow(column(
                        width = 8,
                        offset = 2,
                        plotOutput("pca", height = "600px")
                    ))
                ),
        # kegg tab content
        tabItem(tabName = "kegg",
                tabsetPanel(
                    tabPanel(
                    "All DE genes",
                    hr(),
                    h3("All pathways"),
                    fluidRow(
                      column(
                      width = 8,
                      offset = 2,
                      DTOutput("tableAll")
                    )),
                    hr(),
                    h3("BarPlot"),
                    fluidRow(
                      class = "text-center",
                      column(
                        align = "center",
                        offset = 2,
                        plotlyOutput("keggPlotAll"),
                        width = 8
                    )),
                    hr(),
                    h3("ChordPlot"),
                    fluidRow(
                      column(
                        align = "center",
                        offset = 2,
                        chorddiagOutput("keggChordAll", width = "700px", height = "700px"),
                        width = 8
                    )),
                    hr(),
                    h3("DotPlot"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("keggDotAll"),
                        width = 8
                    )),
                    hr(),
                    h3("Heatmap"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("heatmapKeggAll"),
                        width = 8
                      )),
                    hr(),
                    h3("NetPlot"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("cnetKeggAll"),
                        width = 8
                    ))
                  ),
                  tabPanel(
                    "Upregulated",
                    hr(),
                    h3("All pathways"),
                    fluidRow(
                      column(
                      width = 8,
                      offset = 2,
                      DTOutput("table")
                    )),
                    hr(),
                    h3("BarPlot"),
                    fluidRow(
                      class = "text-center",
                      column(
                        align = "center",
                        offset = 2,
                        plotlyOutput("keggPlot"),
                        width = 8
                    )),
                    hr(),
                    h3("ChordPlot"),
                    fluidRow(
                      column(
                        align = "center",
                        offset = 2,
                        chorddiagOutput("keggChord", width = "700px", height = "700px"),
                        width = 8
                    )),
                    hr(),
                    h3("DotPlot"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("keggDotUp"),
                        width = 8
                    )),
                    hr(),
                    h3("Heatmap"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("heatmapKeggUp"),
                        width = 8
                      )),
                    hr(),
                    h3("NetPlot"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("cnetKeggUp"),
                        width = 8
                    ))
                  ), # fin tabpanel upregulated
                  tabPanel(
                    "Downregulated",
                    hr(),
                    h3("All pathways"),
                    fluidRow(
                      column(
                      width = 8,
                      offset = 2,
                      DTOutput("tableDown")
                    )),
                    hr(),
                    h3("BarPlot"),
                    fluidRow(
                      class = "text-center",
                      column(
                        align = "center",
                        offset = 2,
                        plotlyOutput("keggPlotDown"),
                        width = 8
                    )),
                    hr(),
                    h3("ChordPlot"),
                    fluidRow(
                      column(
                        align = "center",
                        offset = 2,
                        chorddiagOutput("keggChordDown", width = "700px", height = "700px"),
                        width = 8
                    )),
                    hr(),
                    h3("DotPlot"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("keggDotDown"),
                        width = 8
                    )),
                    hr(),
                    h3("Heatmap"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("heatmapKeggDown"),
                        width = 8
                      )
                    ),
                    hr(),
                    h3("NetPlot"),
                    fluidRow(
                      class="text-center",
                      column(
                        align = "center",
                        offset= 2,
                        plotOutput("cnetKeggDown"),
                        width = 8
                    ))
                  ) # fin tabpanel
                )),
        tabItem( tabName = "go", # GO tab GO tab
          tabsetPanel(
            tabPanel("All DE genes",
                     h3("Biological proccess"),
                     fluidRow(column(
                       # table BP
                       width = 8,
                       offset = 2,
                       dataTableOutput("tableBPall")
                     )),
                     hr(),
                     fluidRow(
                       #plot BP
                       class = "text-center",
                       column(
                         align = "center",
                         offset = 2,
                         plotlyOutput("plotBPall"),
                         width = 8)),
                     hr(),
                     fluidRow(
                       class="text-center",
                       column(
                         align = "center",
                         offset= 2,
                         plotOutput("BPDotall"),
                         width = 8)),
                     h3("Molecular Functions"),
                     fluidRow(column(
                       # table MF
                       width = 8,
                       offset = 2,
                       dataTableOutput("tableMFall")
                     )),
                     hr(),
                     fluidRow(# plot MF
                       class = "text-center",
                       column( align = "center",offset = 2,plotlyOutput("plotMFall"),width = 8)
                     ),
                     hr(),
                     fluidRow(
                       class="text-center",
                       column(
                         align = "center",
                         offset= 2,
                         plotOutput("MFDotall"),
                         width = 8
                       )
                     ),
                     h3("Cellular components"),
                     fluidRow( # table CC
                       column(width = 8,offset = 2,dataTableOutput("tableCCall"))
                     ),
                     hr(),
                     fluidRow(# plot CC
                       class = "text-center",
                       column(align = "center",offset = 2,plotlyOutput("plotCCall"),width = 8)
                     ),
                     hr(),
                     fluidRow(
                       class="text-center",
                       column(
                         align = "center",
                         offset= 2,
                         plotOutput("CCDotall"),
                         width = 8
                       )
                     ) #fin fluidrow
            ),
            tabPanel("Upregulated",
            h3("Biological proccess"),
            fluidRow(column(
                # table BP
                width = 8,
                offset = 2,
                dataTableOutput("tableBP")
            )),
            hr(),
            fluidRow(
                #plot BP
                class = "text-center",
                column(
                    align = "center",
                    offset = 2,
                    plotlyOutput("plotBP"),
                    width = 8)),
            hr(),
            fluidRow(
              class="text-center",
              column(
                align = "center",
                offset= 2,
                plotOutput("BPDotUp"),
                width = 8)),
            h3("Molecular Functions"),
            fluidRow(column(
                # table MF
                width = 8,
                offset = 2,
                dataTableOutput("tableMF")
            )),
            hr(),
            fluidRow(# plot MF
                class = "text-center",
                column( align = "center",offset = 2,plotlyOutput("plotMF"),width = 8)
            ),
            hr(),
            fluidRow(
              class="text-center",
              column(
                align = "center",
                offset= 2,
                plotOutput("MFDotUp"),
                width = 8
              )
            ),
            h3("Cellular components"),
            fluidRow( # table CC
              column(width = 8,offset = 2,dataTableOutput("tableCC"))
              ),
            hr(),
            fluidRow(# plot CC
                class = "text-center",
                column(align = "center",offset = 2,plotlyOutput("plotCC"),width = 8)
            ),
            hr(),
            fluidRow(
              class="text-center",
              column(
                align = "center",
                offset= 2,
                plotOutput("CCDotUp"),
                width = 8
              )
            ) #fin fluidrow
        ),
        tabPanel("Downregulated",
                 h3("Biological proccess"),
                 fluidRow(column(# table BP
                   width = 8,
                   offset = 2,
                   dataTableOutput("tableBPdown")
                 )),
                 hr(),
                 fluidRow(#plot BP
                   class = "text-center",
                   column(
                     align = "center",
                     offset = 2,
                     plotlyOutput("plotBPdown"),
                     width = 8
                   )
                 ),
                 hr(),
                 fluidRow(
                   class="text-center",
                   column(
                     align = "center",
                     offset= 2,
                     plotOutput("BPDotDown"),
                     width = 8)),
                 h3("Molecular Functions"),
                 fluidRow(column(# table MF
                   width = 8,
                   offset = 2,
                   dataTableOutput("tableMFdown")
                 )),
                 hr(),
                 fluidRow(# plot MF
                   class = "text-center",
                   column( align = "center",offset = 2,plotlyOutput("plotMFdown"),width = 8)
                 ),
                 hr(),
                 fluidRow(
                   class="text-center",
                   column(
                     align = "center",
                     offset= 2,
                     plotOutput("MFDotDown"),
                     width = 8)),
                 h3("Cellular components"),
                 fluidRow( # table CC
                   column(width = 8,offset = 2,dataTableOutput("tableCCdown"))
                 ),
                 hr(),
                 fluidRow(# plot CC
                   class = "text-center",
                   column(align = "center",offset = 2,plotlyOutput("plotCCdown"),width = 8)
                 ),
                 hr(),
                 fluidRow(
                   class="text-center",
                   column(
                     align = "center",
                     offset= 2,
                     plotOutput("CCDotDown"),
                     width = 8)) #fin fluidrow
        ))), # tab GO
        tabItem(tabName = "gsea",
                h3("Gene Set Enrichment Analysis"),
                fluidRow(column(
                  width = 8,
                  offset = 2,
                  dataTableOutput("gseaTable")
                )),
                hr(),
                fluidRow(column(
                  width = 8,
                  offset = 2,
                  plotOutput("gseaPlot")
                ))
                ) #fin tab GSEA
    ) # fin tab items
)# fin dashboardbody

########################################## UI #################################################

ui <- dashboardPage(title="Rnaseq viewer and report",
                    header,
                    sidebar,
                    body
                    ) # fin del UI

########################################## SERVER #################################################
server <- function(input, output) {
    
  observeEvent(input$aboutButton, {
            shinyalert("Enrich app 2020", "Authors:
            Miriam Riquelme Pérez (corresponding author)
            Fernando Pérez Sanz
            For any suggestion or bug, please contact us
            miriam.riquelmep@gmail.com", type="info")})
  
    data <- reactiveValues() # genes
    goDT <- reactiveValues() #pretabla GO
    kgg <- reactiveValues() # enrich kegg
    go <- reactiveValues() # enrich GO
    kggDT <- reactiveValues() # pretabla kegg
    datos <- reactiveValues(dds=NULL) #objetos dds post DESeq()
    gsea <- reactiveValues() # objeto GSEA
    logfcRange <- reactiveValues() # min y max logfc

    
    observeEvent(input$deseqFile, {
      datos$dds <- readRDS(input$deseqFile$datapath)
      saveRDS(datos$dds, "tmpResources/dds.Rds")
      
      res.sh <- as.data.frame(lfcShrink(datos$dds, coef=2, type="apeglm", res = results(datos$dds)))
      
      logfcRange$min <- min(res.sh$log2FoldChange)
      logfcRange$max <- max(res.sh$log2FoldChange)
    })
    
    observeEvent(input$runEnrich, {
        data$genesUp <- getSigUpregulated(datos$dds, padj(), logfc()[2])
        data$genesDown <- getSigDownregulated(datos$dds, padj(), logfc()[1])
        data$genesall <- rbind(data$genesUp, data$genesDown)
        saveRDS(data$genesall, "tmpResources/genesall.Rds")
        saveRDS(data$genesUp, "tmpResources/genesUp.Rds")
        saveRDS(data$genesDown, "tmpResources/genesDown.Rds")
        
        kgg$all <- customKegg(data$genesall, species = "Mm", species.KEGG = "mmu")
        saveRDS(kgg$all, "tmpResources/kggAll.Rds")
        kggDT$all <- kegg2DT(kgg$all, data$genesall)
        saveRDS(kggDT$all, "tmpResources/kggDTall.Rds")
        
        kgg$up <- customKegg(data$genesUp, species = "Mm", species.KEGG = "mmu")
        saveRDS(kgg$up, "tmpResources/kggUp.Rds")
        kggDT$up <- kegg2DT(kgg$up, data$genesUp)
        saveRDS(kggDT$up, "tmpResources/kggDTup.Rds")
        
        kgg$down <- customKegg(data$genesDown, species = "Mm", species.KEGG = "mmu")
        saveRDS(kgg$down, "tmpResources/kggDown.Rds")
        kggDT$down <- kegg2DT(kgg$down, data$genesDown)
        saveRDS(kggDT$down, "tmpResources/kggDTdown.Rds")
        
        go$all <- customGO(data$genesall, species = "Mm")
        saveRDS(go$all, "tmpResources/goAll.Rds")
        goDT$all <- go2DT(enrichdf = go$all, data = data$genesall )
        saveRDS(goDT$all, "tmpResources/goDTall.Rds")
        
        go$up <- customGO(data$genesUp, species = "Mm")
        saveRDS(go$up, "tmpResources/goUp.Rds")
        goDT$up <- go2DT(enrichdf = go$up, data = data$genesUp )
        saveRDS(goDT$up, "tmpResources/goDTup.Rds")
        
        go$down <- customGO(data$genesDown, species = "Mm")
        saveRDS(go$down, "tmpResources/goDown.Rds")
        goDT$down <- go2DT(enrichdf = go$down, data = data$genesDown )
        saveRDS(goDT$down, "tmpResources/goDTdown.Rds")
    })
  # generate reactive variable ###################
    rowsAll <- reactive({input$tableAll_rows_selected})
    rows <- reactive({input$table_rows_selected})
    bprowsall <- reactive({input$tableBPall_rows_selected}) 
    mfrowsall <- reactive({input$tableMFall_rows_selected})
    ccrowsall <- reactive({input$tableCCall_rows_selected})
    bprows <- reactive({input$tableBP_rows_selected})
    mfrows <- reactive({input$tableMF_rows_selected})
    ccrows <- reactive({input$tableCC_rows_selected})
    rowsdown <- reactive({input$tableDown_rows_selected})
    bprowsdown <- reactive({input$tableBPdown_rows_selected})
    mfrowsdown <- reactive({input$tableMFdown_rows_selected})
    ccrowsdown <- reactive({input$tableCCdown_rows_selected})
    variables <- reactive({input$variables})
    gsearow <- reactive({input$gseaTable_rows_selected})
    specie <- reactive({input$specie})
    padj <- reactive({input$padj})
    logfc <- reactive({input$logfc})
    specie <- reactive({input$specie})
# ui selector sample groups ###################
    output$sampleGroup <- renderUI({
        validate(need(datos$dds, ""))
        nvars <- colData(datos$dds) %>% 
                    as.data.frame() %>% 
                    select(-c(sizeFactor,replaceable)) %>% 
                    names()
        selectInput("variables", label="Select condition[s] to plot PCA",
                    choices = nvars,
                    multiple = TRUE)
    })
# ui selector specie ####################
    output$specie <- renderUI({
      validate(need(datos$dds, ""))
      selectInput("specie", label = "Select specie",
                  choices = list("Human" = "Hs", "Mouse"="Mm"), 
                  selected = "Mm")
    })
# ui selector logfc #######################
    output$logfc <- renderUI({
      validate(need(datos$dds, ""))
      sliderInput("logfc", label = "Select logFC range to remove (keep tails)",
                  min=round(logfcRange$min,3), max=round(logfcRange$max, 3),
                  #value = c(round(logfcRange$min,3)+1,round(logfcRange$max,3)-1 ), step = 0.1 )
                  value = c(-0.5,0.5), step = 0.1 )
    })

# ui selector padj #############################
    output$padj <- renderUI({
      validate(need(datos$dds,""))
      sliderInput("padj", label = "Select p-adjusted threshold", min = 0, max=0.2, value=0.05, step = 0.005 )
    })
# preview samples ###################
    output$samples <- DT::renderDataTable(server = TRUE,{
      validate(need(datos$dds, "Load file to render table"))
      metadata <- as.data.frame(colData(datos$dds)) %>% select(-c(sizeFactor,replaceable))
      datatable( metadata, extensions = "Buttons",
                 rownames=FALSE,
                 filter = list(position="top", clear=FALSE),
                 options = list(
                   columnDefs = list(list(orderable = TRUE,
                                          className = "details-control",
                                          targets = 1),
                                     list(className = "dt-right", targets = 1:(ncol(metadata)-1))
                   ),
                   dom = "Bfrtipl",
                   buttons = c("copy", "csv", "excel", "pdf", "print"),
                   list(pageLength = 10, white_space = "normal")
                 )
      )
    })  
# preview table ###################
    output$preview <- DT::renderDT(server=TRUE,{
        validate(need(datos$dds, "Load file to render table"))
        res.sh <- as.data.frame(lfcShrink(datos$dds, coef=2, type="apeglm", res = results(datos$dds)))
        conversion <- geneIdConverter(rownames(res.sh))
        res.sh$baseMean <- round(res.sh$baseMean,4)
        res.sh$lfcSE <- round(res.sh$lfcSE,4)
        res.sh$log2FoldChange <- round(res.sh$log2FoldChange,4)
        res.sh <- cbind(`Description`=conversion$description, res.sh)
        res.sh <- cbind(`GeneName/Symbol`=conversion$consensus, res.sh)
        res.sh <- res.sh[ ((res.sh$log2FoldChange >= logfc()[2] |
                       res.sh$log2FoldChange< logfc()[1]) &
                       res.sh$padj <= padj() ),]
        res.sh <-  res.sh %>% select(-c(pvalue))
        links = paste0("<a href='http://www.ensembl.org/Mus_musculus/Gene/Summary?db=core;g=",
                            rownames(res.sh),"' target='_blank'>",rownames(res.sh),"</a>")
        res.sh <- cbind(`GeneName/Ensembl`= links, res.sh)
        #add_column(res, Symbol=conversion$consensus, .before = "baseMean")
        datatable( res.sh, extensions = "Buttons", escape = FALSE, 
                  rownames = FALSE,
                  filter = list(position="top", clear=FALSE),
                  options = list(
                  columnDefs = list(list(orderable = FALSE,
                                         className = "details-control",
                                         targets = 1),
                                    list(className = "dt-right", targets = 1:ncol(res))
                                    ),
                  rowCallback = JS(
                                "function(row, data) {",
                                "for (i = 6; i < 8; i++) {",
                                "if (data[i]>1000 | data[i]<1){",
                                "$('td:eq('+i+')', row).html(data[i].toExponential(3));",
                                "}",
                                "}",
                                "}"),
                  dom = "Bfrtipl",
                  buttons = c("copy", "csv", "excel", "pdf", "print"),
                  list(pageLength = 10, white_space = "normal")
                  )
                  )
    })
# view pca plot data ###################
    output$pca <- renderPlot( {
        validate(need(datos$dds, "Load file and condition to render PCA"))
        validate(need(variables(),"Load condition to render PCA" ) )
        plotPCA(rlog(datos$dds), intgroup = variables() )+
            theme(plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm"))+
            theme(text = element_text(size=20))
        })
# KEGG table All #####################################
    output$tableAll <- DT::renderDT(server=TRUE,{
        validate(need(kgg$all, "Load file to render table"))
        kgg <- kgg$all
        predata <- kggDT$all
        datatable2(
            predata,
            vars = c("genes"),
            filter = list(position="top", clear=FALSE),
            escape = FALSE,
            opts = list(pageLength = 10, white_space = "normal"))
        }) 
# KEGG barplot All ################
    output$keggPlotAll <- renderPlotly ({
        validate(need(kgg$all, "Load file to render BarPlot"))
        kgg <- kgg$all
        nr <- rowsAll()
        if(is.null(nr)){nr <- c(1:10)}
        plotKegg(enrichdf = kgg[nr,], nrows = length(nr))
    })
# KEGG chordiag plot All ###############
    output$keggChordAll <- renderChorddiag({
        validate(need(kgg$all, "Load file to render ChordPlot"))
        kgg <- kgg$all
        nr <- rowsAll()
        if(is.null(nr)){nr <- c(1:10)}
        chordPlot(kgg[nr, ], nRows = length(nr), orderby = "P.DE")
    })
# KEGG dotplot All ################### 
    output$keggDotAll <- renderPlot({
      validate(need(kgg$all, "Load file and select to render dotPlot"))
      validate(need(rowsAll(), "Select the paths of interest to render DotPlot"))
      kgg <- kgg$all
      nr <- rowsAll()
      if(is.null(nr)){nr <- c(1:20)}
      dotPlotkegg(kgg[nr,], n = length(nr))
    })
# KEGG heatmap All #################
    output$heatmapKeggAll <- renderPlot({
      validate(need(kgg$all, "Load file and select to render Heatmap"))
      validate(need(rowsAll(), "Select the paths of interest to render HeatMap"))
      validate(need(kggDT$all, ""))
      nr <- rowsAll()
      heatmapKegg(kggDT$all, nr)
    })
# KEGG cnet All #################
    output$cnetKeggAll <- renderPlot({
      validate(need(kgg$all, "Load file and select to render Net Plot"))
      validate(need(rowsAll(), "Select the paths of interest to render NetPlot"))
      nr <- rowsAll()
      customCnetKegg(kgg$all, nr)
    })
# KEGG table up#####################################
    output$table <- DT::renderDT(server=TRUE,{
        validate(need(kgg$up, "Load file to render table"))
        kgg <- kgg$up
        predata <- kggDT$up
        datatable2(
            predata,
            vars = c("genes"),
            filter = list(position="top", clear=FALSE),
            escape = FALSE,
            opts = list(pageLength = 10, white_space = "normal"))
        }) 
# KEGG barplot up################
    output$keggPlot <- renderPlotly ({
        validate(need(kgg$up, "Load file to render BarPlot"))
        kgg <- kgg$up
        nr <- rows()
        if(is.null(nr)){nr <- c(1:10)}
        plotKegg(enrichdf = kgg[nr,], nrows = length(nr))
    })
# KEGG chordiag plot up ###############
    output$keggChord <- renderChorddiag({
        validate(need(kgg$up, "Load file to render ChordPlot"))
        kgg <- kgg$up
        nr <- rows()
        if(is.null(nr)){nr <- c(1:10)}
        chordPlot(kgg[nr, ], nRows = length(nr), orderby = "P.DE")
    })
# KEGG dotplot UP ################### 
    output$keggDotUp <- renderPlot({
      validate(need(kgg$up, "Load file and select to render dotPlot"))
      validate(need(rows(), "Select the paths of interest to render DotPlot"))
      kgg <- kgg$up
      nr <- rows()
      if(is.null(nr)){nr <- c(1:20)}
      dotPlotkegg(kgg[nr,], n = length(nr))
    })
# KEGG heatmap Up #################
    output$heatmapKeggUp <- renderPlot({
      validate(need(kgg$up, "Load file and select to render Heatmap"))
      validate(need(rows(), "Select the paths of interest to render HeatMap"))
      validate(need(kggDT$up, ""))
      nr <- rows()
      heatmapKegg(kggDT$up, nr)
    })
# KEGG cnet Up #################
    output$cnetKeggUp <- renderPlot({
      validate(need(kgg$up, "Load file and select to render Net Plot"))
      validate(need(rows(), "Select the paths of interest to render NetPlot"))
      nr <- rows()
      customCnetKegg(kgg$up, nr)
    })
    
# KEGG table down #####################################
    output$tableDown <- DT::renderDT(server=TRUE,{
      validate(need(kgg$down, "Load file to render table"))
      kgg <- kgg$down
      predata <- kggDT$down
      datatable2(
        predata,
        vars = c("genes"),
        filter = list(position="top", clear=FALSE),
        escape = FALSE,
        opts = list(pageLength = 10, white_space = "normal"))
    }) 
# KEGG barplot down ################
    output$keggPlotDown <- renderPlotly ({
      validate(need(kgg$down, "Load file to render BarPlot"))
      kgg <- kgg$down
      nrdown <- rowsdown()
      if(is.null(nrdown)){nrdown <- c(1:10)}
      plotKegg(enrichdf = kgg[nrdown,], nrows = length(nrdown))
    })
# KEGG chordiag plot down ###############
    output$keggChordDown <- renderChorddiag({
      validate(need(kgg$down, "Load file to render ChordPlot"))
      kgg <- kgg$down
      nrdown <- rowsdown()
      if(is.null(nrdown)){nrdown <- c(1:10)}
      chordPlot(kgg[nrdown, ], nRows = length(nrdown), orderby = "P.DE")
    })
# KEGG dotplot Down ################### 
    output$keggDotDown <- renderPlot({
      validate(need(kgg$down, "Load file to render DotPlot"))
      validate(need(rowsdown(), "Select the paths of interest to render dotPlot"))
      kgg <- kgg$down
      nrdown <- rowsdown()
      if(is.null(nrdown)){nrdown <- c(1:20)}
      dotPlotkegg(kgg[nrdown,], n = length(nrdown))
    })
# KEGG heatmap Down #################
    output$heatmapKeggDown <- renderPlot({
      validate(need(kgg$down, "Load file to render Heatmap"))
      validate(need(rowsdown(), "Select the paths of interest to render Heatmap"))
      nrdown <- rowsdown()
      heatmapKegg(kggDT$down, nrdown)
    })
# KEGG cnet Down #################
    output$cnetKeggDown <- renderPlot({
      validate(need(kgg$down, "Load file to render NetPlot"))
      validate(need(rowsdown(), "Select the paths of interest to render NetPlot"))
      nrdown <- rowsdown()
      customCnetKegg(kgg$down, nrdown)
    })
# GO table BP ALL #####################
    output$tableBPall <- DT::renderDataTable(server=TRUE,{
      validate(need(goDT$all, "Load file to render table"))
      goDT <- goDT$all 
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal")
      )
    })
    # GO plots BP all #####################
    output$plotBPall <- renderPlotly({
      validate(need(go$all, "Load file to render plot"))
      gos <- go$all
      bpnr <- bprowsall()
      if(is.null(bpnr)){bpnr <- c(1:10)}
      gosBP <- gos[gos$Ont=="BP",]
      plotGO(enrichdf = gosBP[bpnr, ], nrows = length(bpnr), ont="BP")
    })
    # GO BP dotplot all ################### 
    output$BPDotall <- renderPlot({
      validate(need(go$all, "Load file to render dotPlot"))
      validate(need(bprowsall(), "Select the terms of interest to render DotPlot"))
      gos <- go$all
      bpnr <- bprowsall()
      if(is.null(bpnr)){bpnr <- c(1:20)}
      gosBP <- gos[gos$Ont=="BP",]
      dotPlotGO(gosBP[bpnr,], n = length(bpnr))
    })
    # GO table MF all #####################
    output$tableMFall <- DT::renderDataTable({
      validate(need(goDT$all, "Load file to render table"))
      goDT <- goDT$all
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal",
                             ajax = list(serverSide = TRUE, processing = TRUE))
      )
    })
    # GO plots MF all  #####################
    output$plotMFall <- renderPlotly({
      validate(need(go$all, "Load file to render plot"))
      gos <- go$all
      mfnr <- mfrowsall()
      if(is.null(mfnr)){mfnr <- c(1:10)}
      gosMF <- gos[gos$Ont=="MF",]
      plotGO(enrichdf = gosMF[mfnr, ], nrows = length(mfnr), ont = "MF")
    })
    # GO MF dotplot all ################### 
    output$MFDotall <- renderPlot({
      validate(need(go$all, "Load file to render dotPlot"))
      validate(need(mfrowsall(), "Select the terms of interest to render DotPlot"))
      gos <- go$all
      mfnr <- mfrowsall()
      if(is.null(mfnr)){mfnr <- c(1:20)}
      gosMF <- gos[gos$Ont=="MF",]
      dotPlotGO(gosMF[mfnr,], n = length(mfnr))
    })
    # GO table CC all #####################
    output$tableCCall <- DT::renderDataTable(server=TRUE,{
      validate(need(goDT$all, "Load file to render table"))
      goDT <- goDT$all
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal",
                             ajax = list(serverSide = TRUE, processing = TRUE))
      )
    })
    # GO plots CC all #####################
    output$plotCCall <- renderPlotly({
      validate(need(go$all, "Load file to render plot"))
      gos <- go$all
      ccnr <- ccrowsall()
      if(is.null(ccnr)){ccnr <- c(1:10)}
      gosCC <- gos[gos$Ont=="CC",]
      plotGO(enrichdf = gosCC[ccnr,], nrows = length(ccnr), ont="CC")
    })
    # GO CC dotplot all ################### 
    output$CCDotall <- renderPlot({
      validate(need(go$all, "Load file to render dotPlot"))
      validate(need(ccrowsall(), "Select the terms of interest to render DotPlot"))
      gos <- go$all
      ccnr <- ccrowsall()
      if(is.null(ccnr)){ccnr <- c(1:20)}
      gosCC <- gos[gos$Ont=="CC",]
      dotPlotGO(gosCC[ccnr,], n = length(ccnr))
    })

# GO table BP UP#####################
    output$tableBP <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal")
               )
    })
# GO plots BP UP #####################
    output$plotBP <- renderPlotly({
      validate(need(go$up, "Load file to render plot"))
       gos <- go$up
        bpnr <- bprows()
        if(is.null(bpnr)){bpnr <- c(1:10)}
        gosBP <- gos[gos$Ont=="BP",]
        plotGO(enrichdf = gosBP[bpnr, ], nrows = length(bpnr), ont="BP")
    })
# GO BP dotplot up ################### 
    output$BPDotUp <- renderPlot({
      validate(need(go$up, "Load file to render dotPlot"))
      validate(need(bprows(), "Select the terms of interest to render DotPlot"))
      gos <- go$up
      bpnr <- bprows()
      if(is.null(bpnr)){bpnr <- c(1:20)}
      gosBP <- gos[gos$Ont=="BP",]
      dotPlotGO(gosBP[bpnr,], n = length(bpnr))
    })
# GO table MF UP #####################
    output$tableMF <- DT::renderDataTable({
      validate(need(goDT$up, "Load file to render table"))
      goDT <- goDT$up
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal",
                             ajax = list(serverSide = TRUE, processing = TRUE))
      )
    })
# GO plots MF UP #####################
    output$plotMF <- renderPlotly({
        validate(need(go$up, "Load file to render plot"))
        gos <- go$up
        mfnr <- mfrows()
        if(is.null(mfnr)){mfnr <- c(1:10)}
        gosMF <- gos[gos$Ont=="MF",]
        plotGO(enrichdf = gosMF[mfnr, ], nrows = length(mfnr), ont = "MF")
    })
# GO MF dotplot up ################### 
    output$MFDotUp <- renderPlot({
      validate(need(go$up, "Load file to render dotPlot"))
      validate(need(mfrows(), "Select the terms of interest to render DotPlot"))
      gos <- go$up
      mfnr <- mfrows()
      if(is.null(mfnr)){mfnr <- c(1:20)}
      gosMF <- gos[gos$Ont=="MF",]
      dotPlotGO(gosMF[mfnr,], n = length(mfnr))
    })
# GO table CC UP #####################
    output$tableCC <- DT::renderDataTable(server=TRUE,{
      validate(need(goDT$up, "Load file to render table"))
      goDT <- goDT$up
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal",
                             ajax = list(serverSide = TRUE, processing = TRUE))
      )
    })
# GO plots CC UP #####################
    output$plotCC <- renderPlotly({
        validate(need(go$up, "Load file to render plot"))
        gos <- go$up
        ccnr <- ccrows()
        if(is.null(ccnr)){ccnr <- c(1:10)}
        gosCC <- gos[gos$Ont=="CC",]
      plotGO(enrichdf = gosCC[ccnr,], nrows = length(ccnr), ont="CC")
    })
# GO CC dotplot up ################### 
    output$CCDotUp <- renderPlot({
      validate(need(go$up, "Load file to render dotPlot"))
      validate(need(ccrows(), "Select the terms of interest to render DotPlot"))
      gos <- go$up
      ccnr <- ccrows()
      if(is.null(ccnr)){ccnr <- c(1:20)}
      gosCC <- gos[gos$Ont=="CC",]
      dotPlotGO(gosCC[ccnr,], n = length(ccnr))
    })
# GO table BP DOWN #####################
    output$tableBPdown <- DT::renderDataTable(server=TRUE,{
      validate(need(goDT$down, "Load file to render table"))
      goDT <- goDT$down
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal")
      )
    })
    # GO plots BP DOWN #####################
    output$plotBPdown <- renderPlotly({
      validate(need(go$down, "Load file to render plot"))
      gos <- go$down
      bpnrdown <- bprowsdown()
      if(is.null(bpnrdown)){bpnrdown <- c(1:10)}
      gosBP <- gos[gos$Ont=="BP",]
      plotGO(enrichdf = gosBP[bpnrdown, ], nrows = length(bpnrdown), ont="BP")
    })
# GO BP dotplot down ################### 
    output$BPDotDown <- renderPlot({
      validate(need(go$down, "Load file to render dotPlot"))
      validate(need(bprowsdown(), "Select the terms of interest to render DotPlot"))
      gos <- go$down
      bpnrdown <- bprowsdown()
      if(is.null(bpnrdown)){bpnrdown <- c(1:20)}
      gosBP <- gos[gos$Ont=="BP",]
      dotPlotGO(gosBP[bpnrdown,], n = length(bpnrdown))
    })
# GO table MF DOWN #####################
    output$tableMFdown <- DT::renderDataTable({
      validate(need(goDT$down, "Load file to render table"))
      goDT <- goDT$down
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal",
                             ajax = list(serverSide = TRUE, processing = TRUE))
      )
    })
# GO plots MF DOWN #####################
    output$plotMFdown <- renderPlotly({
      validate(need(go$down, "Load file to render plot"))
      gos <- go$down
      mfnrdown <- mfrowsdown()
      if(is.null(mfnrdown)){mfnrdown <- c(1:10)}
      gosMF <- gos[gos$Ont=="MF",]
      plotGO(enrichdf = gosMF[mfnrdown, ], nrows = length(mfnrdown), ont = "MF")
    })
# GO MF dotplot down ################### 
    output$MFDotDown <- renderPlot({
      validate(need(go$down, "Load file to render dotPlot"))
      validate(need(mfrowsdown(), "Select the terms of interest to render DotPlot"))
      gos <- go$down
      mfnrdown <- mfrowsdown()
      if(is.null(mfnrdown)){mfnrdown <- c(1:20)}
      gosMF <- gos[gos$Ont=="MF",]
      dotPlotGO(gosMF[mfnrdown,], n = length(mfnrdown))
    })
    # GO table CC DOWN #####################
    output$tableCCdown <- DT::renderDataTable(server=TRUE,{
      validate(need(goDT$down, "Load file to render table"))
      goDT <- goDT$down
      names(goDT)[names(goDT) == "level"] <- "Ont.level"
      goDT$Ont.level = as.integer(goDT$Ont.level) 
      datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
                 filter = list(position="top", clear=FALSE),
                 escape = FALSE,
                 opts = list(pageLength = 10, white_space = "normal",
                             ajax = list(serverSide = TRUE, processing = TRUE))
      )
    })
    # GO plots CC DOWN #####################
    output$plotCCdown <- renderPlotly({
      validate(need(go$down, "Load file to render plot"))
      gos <- go$down
      ccnrdown <- ccrowsdown()
      if(is.null(ccnrdown)){ccnrdown <- c(1:10)}
      gosCC <- gos[gos$Ont=="CC",]
      plotGO(enrichdf = gosCC[ccnrdown,], nrows = length(ccnrdown), ont="CC")
    })
# GO CC dotplot down ################### 
    output$CCDotDown <- renderPlot({
      validate(need(go$down, "Load file to render dotPlot"))
      validate(need(ccrowsdown(), "Select the terms of interest to render DotPlot"))
      gos <- go$down
      ccnrdown <- ccrowsdown()
      if(is.null(ccnrdown)){ccnrdown <- c(1:20)}
      gosCC <- gos[gos$Ont=="CC",]
      dotPlotGO(gosCC[ccnrdown,], n = length(ccnrdown))
    })
# GSEA table ##########################
    output$gseaTable <- renderDataTable({
      validate(need(datos$dds, "Load file to render table"))
      gsea$gsea <- gseaKegg(datos$dds)
      mygsea <- gsea$gsea
      saveRDS(mygsea, "tmpResources/gsea.Rds")
      table <- mygsea@result[mygsea@result$p.adjust<=0.05 ,2:9] %>% 
        mutate_at(vars(3:7), ~round(., 4))
      DT::datatable( table,
                 rownames=FALSE,
                 filter = list(position="top", clear=FALSE),
                 options = list(
                   columnDefs = list(list(orderable = FALSE,
                                          className = "details-control",
                                          targets = 1)
                   ),
                   dom = "Bfrtipl",
                   buttons = c("copy", "csv", "excel", "pdf", "print"),
                   list(pageLength = 10, white_space = "normal")
                 )
      )
    })
# GSEA plot ##########################
    output$gseaPlot <- renderPlot({
      validate(need(gsea$gsea, "Load file to render table"))
      gseanr <- gsearow()
      if(is.null(gseanr)){gseanr <- c(1)}
        enrichplot::gseaplot2(gsea$gsea, geneSetID = gseanr, pvalue_table = TRUE, ES_geom = "line")
    })
# author name ######################
    author <- reactive({input$author})
# generate report #############################
    output$report <- renderUI({
        #validate(need(datos$dds, ""))
        downloadButton("report2", "Generate report")
      
    })
    output$pdf <- renderUI({
      #validate(need(datos$dds, ""))
      downloadButton("reportpdf", "Generate pdf report")
    })
    output$report2 <- downloadHandler(
        # For PDF output, change this to "report.pdf"
        filename = "report.html",
        content = function(file) {
            tempReport <- file.path(tempdir(), "flexReport.Rmd")
            file.copy("flexReport.Rmd", tempReport, overwrite = TRUE)
            file.copy("utils.R", file.path(tempdir(),"utils.R"), overwrite = TRUE)
            file.copy("tmpResources/", tempdir(), overwrite = TRUE, recursive = TRUE)
            do.call(file.remove, list(list.files("tmpResources/", full.names = TRUE)))
            
            nr <- rows()
            nrdown <- rowsdown()
            bpnr <- bprows()
            mfnr <- mfrows()
            ccnr <- ccrows()
            bpnrdown <- bprowsdown()
            mfnrdown <- mfrowsdown()
            ccnrdown <- ccrowsdown()
            variablepca <- variables()
            gseanr <- gsearow()
            nrall <- rowsAll()
            bpnrall <- bprowsall()
            mfnrall <- mfrowsall()
            ccnrall <- ccrowsall()
            if(is.null(gseanr)){gseanr <- c(1)}
            if(is.null(nr)){nr <- c(1:10)}
            if(is.null(ccnr)){ccnr <- c(1:10)}
            if(is.null(mfnr)){mfnr <- c(1:10)}
            if(is.null(bpnr)){bpnr <- c(1:10)}
            if(is.null(nrdown)){nrdown <- c(1:10)}
            if(is.null(ccnrdown)){ccnrdown <- c(1:10)}
            if(is.null(mfnrdown)){mfnrdown <- c(1:10)}
            if(is.null(bpnrdown)){bpnrdown <- c(1:10)}
            if(is.null(nrall)){nrall <- c(1:10)}
            if(is.null(bpnrall)){bpnrall <- c(1:10)}
            if(is.null(mfnrall)){mfnrall <- c(1:10)}
            if(is.null(ccnrall)){ccnrall <- c(1:10)}
            if(is.null(variablepca)){variablepca=NULL}
            params <- list(nr=nr, nrdown=nrdown, bpnr=bpnr, bpnrdown=bpnrdown,
                           mfnr=mfnr, mfnrdown=mfnrdown, ccnr=ccnr, ccnrdown=ccnrdown,
                           variablepca=variablepca, tempdir =tempdir(),
                           gseanr=gseanr, author=author(), nrall = nrall,
                           bpnrall=bpnrall, mfnrall=mfnrall, ccnrall=ccnrall)
            rmarkdown::render(
                tempReport,
                output_file = file,
                params = params,
                envir = new.env(parent = globalenv())
            )
        } )
    output$reportpdf <- downloadHandler(
        # For PDF output, change this to "report.pdf"
        filename = "report.pdf",
        content = function(file) {
            tempReport <- file.path(tempdir(), "pdfReport.Rmd")
            file.copy("pdfReport.Rmd", tempReport, overwrite = TRUE)
            file.copy("utils.R", file.path(tempdir(),"utils.R"), overwrite = TRUE)
            file.copy("tmpResources/", tempdir(), overwrite = TRUE, recursive = TRUE)
            do.call(file.remove, list(list.files("tmpResources/", full.names = TRUE)))
            nr <- rows()
            nrdown <- rowsdown()
            bpnr <- bprows()
            mfnr <- mfrows()
            ccnr <- ccrows()
            bpnrdown <- bprowsdown()
            mfnrdown <- mfrowsdown()
            ccnrdown <- ccrowsdown()
            variablepca <- variables()
            gseanr <- gsearow()
            nrall <- rowsAll()
            bpnrall <- bprowsall()
            mfnrall <- mfrowsall()
            ccnrall <- ccrowsall()
            if(is.null(gseanr)){gseanr <- c(1)}
            if(is.null(nr)){nr <- c(1:10)}
            if(is.null(ccnr)){ccnr <- c(1:10)}
            if(is.null(mfnr)){mfnr <- c(1:10)}
            if(is.null(bpnr)){bpnr <- c(1:10)}
            if(is.null(nrdown)){nrdown <- c(1:10)}
            if(is.null(ccnrdown)){ccnrdown <- c(1:10)}
            if(is.null(mfnrdown)){mfnrdown <- c(1:10)}
            if(is.null(bpnrdown)){bpnrdown <- c(1:10)}
            if(is.null(nrall)){nrall <- c(1:10)}
            if(is.null(bpnrall)){bpnrall <- c(1:10)}
            if(is.null(mfnrall)){mfnrall <- c(1:10)}
            if(is.null(ccnrall)){ccnrall <- c(1:10)}
            if(is.null(variablepca)){variablepca=NULL}
            params <- list(nr=nr, nrdown=nrdown, bpnr=bpnr, bpnrdown=bpnrdown,
                           mfnr=mfnr, mfnrdown=mfnrdown, ccnr=ccnr, ccnrdown=ccnrdown,
                           variablepca=variablepca, tempdir =tempdir(),
                           gseanr=gseanr, author=author(), nrall = nrall,
                           bpnrall=bpnrall, mfnrall=mfnrall, ccnrall=ccnrall)
            rmarkdown::render(
                tempReport,
                output_file = file,
                params = params,
                envir = new.env(parent = globalenv())
            )
        } )
}


shinyApp(ui, server)

