library(shinydashboard)
library(AnnotationDbi)
library(org.Mm.eg.db)
library(org.Hs.eg.db)
library(EnsDb.Mmusculus.v79)
library(EnsDb.Hsapiens.v86)
library(limma)
library(tidyverse)
library(DT)
library(purrr)
library(plotly)
library(ggpubr)
library(chorddiag)
library(DESeq2)
library(fgsea)
library(shinyalert)
library(shinyBS)
library(shinyWidgets)
library(shinydashboardPlus)
source("utils.R")
options(shiny.maxRequestSize = 3000*1024^2)

### HEADER ############
header <- dashboardHeader(title = "RNAseq viewer and report App", 
                          titleWidth = 300, 
                          dropdownMenuOutput("messageMenu"),
                          tags$li(class = "dropdown", actionButton("aboutButton", "About"),
                                  style="margin-top:8px; margin-right: 5px")
)
### SIDEBAR ##########
sidebar <- dashboardSidebar(useShinyalert(),
                            sidebarMenu(
                                menuItem(
                                    pickerInput(
                                        inputId = "specie",
                                        label = "Select specie",
                                        choices = list( "Human" = "Hs", "Mouse" = "Mm"),
                                        options = list(title = "specie"),
                                        selected = NULL
                                    ) 
                                )
                            ),
                            sidebarMenu(
                              menuItem(
                                  uiOutput("deseqFile")
                                # fileInput("deseqFile",
                                #           "Choose RDS with DESeq object",
                                #           placeholder = "RDS DESeq", accept = ".Rds")
                                )),
                            sidebarMenu(
                              menuItem("App Information",
                                       tabName = "info",
                                       icon = icon("info")),
                              menuItem("Preview dataset",
                                       tabName = "preview",
                                       icon = icon("eye")),
                              menuItem(
                                "Kegg Enrichment",
                                tabName = "kegg",
                                icon = icon("chart-bar")
                              ),
                              menuItem(
                                "GO Enrichment",
                                tabName = "go",
                                icon = icon("chart-bar")
                              ),
                              menuItem(
                                "GSEA",
                                tabName = "gsea",
                                icon = icon("chart-line")
                              ),
                              sidebarMenu(
                                menuItem(
                                  textInput("author", value="your name...", label = h4("Author report name")
                                  ))),
                              sidebarMenu( 
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("report"))))),
                              sidebarMenu(
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("pdf")))))
                            ))
### BODY ###############
body <- dashboardBody(
    setShadow(class = "shiny-plot-output"),
    setShadow( class = "box"),
    setShadow( class = "svg-container"),
    shiny::tagList(shiny::tags$head(
        shiny::tags$link(rel = "stylesheet", type = "text/css", href = "busystyle.css"),
        shiny::tags$script(type = "text/javascript", src = "busy.js")
    )),
    div(
        class = "busy",
        h4("Loading data, please be patient..."),
        img(src = "dna-svg-small-13.gif", style = "width: 150px"),
        style = "z-index: 99"
    ), 
  bsAlert("alert"),
  tabItems(
    # Initial INFO
    tabItem(tabName = "info",
            br(),
            fluidRow(column(offset = 2,width = 10,
            box(width=10,
                status = "info",
                title = h1(strong("Welcome to Enrich app 2020!") ),
            h3("Before starting using the app"),
            p("As a necessary initial element to start the analysis, 
                the program imports an object of the type DeseqDataSet, 
                generated by the DESeq function of the", 
              a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
              "library. It has to be compress as an RDS object and upload 
                by clicking on the search engine button found in the upper left 
                corner of the app. Choose your object and enjoy your enrichment analysis ;)"),
            br(),
            h3("How to download the app"),
            p("This app can be found on ",
              a("GitHub.", 
                href = "https://github.com/"))),
    ) )),
    # preview tab
    tabItem(tabName = "preview",
            fluidRow(
                infoBoxOutput("allbox"),
                infoBoxOutput("upbox"),
                infoBoxOutput("downbox"),
            ), # fin fluidrow boxinfos
            fluidRow( 
              column(width = 2, uiOutput("sampleGroup")),
              #column(width = 2, uiOutput("specie")),
              column(width = 3, offset = 1, uiOutput("logfc")),
              column(width = 4, uiOutput("padj")),
              column(width = 2, strong("Click to compute enrichment"), actionButton("runEnrich", "Apply values"))
            ),
            hr(),
            fluidRow(column(width = 8,
                            offset = 2,
                            circleButton(inputId = "info1", icon = icon("info"),
                                         size="xs", status = "primary"),
                            bsTooltip("info1", "Enter free text explaining biological experiment",
                                      trigger = "click", placement = "right"),
                            textAreaInput("biologicalText",
                                          label="Biological context",
                                          resize = "both",
                                          width = "900px",
                                          height = "200px"))),
            hr(),
            h3("Samples info (colData)"),
            fluidRow(
              column(
                width = 8,
                offset = 2,
                dataTableOutput("samples"),
              )
            ),
            hr(),
            h3("DE results"),
            fluidRow(
              column(
                width = 8,
                offset = 2,
                DTOutput("preview")
              )
            ),
            hr(),
            h3("Expression Plots"),
            fluidRow(column(
              width = 5,
              plotOutput("volcano", height = "600px")),
            column(
              width = 7,
              plotOutput("MA", height = "600px"))
            ),
            hr(),
            h3("PCA"),
            fluidRow(column(
              width = 8,
              offset = 2,
              plotOutput("pca", height = "600px")
              )
            ),
            fluidRow(
                column(width = 12,
                       offset = 2,
                    textAreaInput("explainPreview",
                              label="Preview background",
                              resize = "both",
                              width = "800px",
                              height = "200px"))),
    ),
    # kegg tab content
    tabItem(tabName = "kegg",
            tabsetPanel(
              tabPanel(
                "All DE genes",
                hr(),
                fluidRow(column(12,
                                offset = 2,
                                textAreaInput("keggAllText", 
                                                  label = "Kegg all genes",
                                                  resize = "both",
                                                  width = "800px",
                                                  height = "200px"))), 
                hr(),
                h3("All pathways"),
                fluidRow(
                  column(
                    width = 8,
                    offset = 2,
                    DTOutput("tableAll")
                  )),
                hr(),
                h3("BarPlot"),
                fluidRow(
                  class = "text-center",
                  column(
                    align = "center",
                    offset = 2,
                    plotlyOutput("keggPlotAll"),
                    width = 8
                  )),
                hr(),
                h3("ChordPlot"),
                fluidRow(
                  column(
                    align = "center",
                    offset = 2,
                    chorddiagOutput("keggChordAll", width = "700px", height = "700px"),
                    width = 8
                  )),
                hr(),
                h3("DotPlot"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("keggDotAll"),
                    width = 8
                  )),
                hr(),
                h3("Heatmap"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("heatmapKeggAll"),
                    width = 8
                  )),
                hr(),
                h3("NetPlot"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("cnetKeggAll"),
                    width = 8
                  ))
              ),
              tabPanel(
                "Upregulated",
                hr(),
                h3("All pathways"),
                fluidRow(
                  column(
                    width = 8,
                    offset = 2,
                    DTOutput("table")
                  )),
                hr(),
                h3("BarPlot"),
                fluidRow(
                  class = "text-center",
                  column(
                    align = "center",
                    offset = 2,
                    plotlyOutput("keggPlot"),
                    width = 8
                  )),
                hr(),
                h3("ChordPlot"),
                fluidRow(
                  column(
                    align = "center",
                    offset = 2,
                    chorddiagOutput("keggChord", width = "700px", height = "700px"),
                    width = 8
                  )),
                hr(),
                h3("DotPlot"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("keggDotUp"),
                    width = 8
                  )),
                hr(),
                h3("Heatmap"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("heatmapKeggUp"),
                    width = 8
                  )),
                hr(),
                h3("NetPlot"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("cnetKeggUp"),
                    width = 8
                  ))
              ), # fin tabpanel upregulated
              tabPanel(
                "Downregulated",
                hr(),
                h3("All pathways"),
                fluidRow(
                  column(
                    width = 8,
                    offset = 2,
                    DTOutput("tableDown")
                  )),
                hr(),
                h3("BarPlot"),
                fluidRow(
                  class = "text-center",
                  column(
                    align = "center",
                    offset = 2,
                    plotlyOutput("keggPlotDown"),
                    width = 8
                  )),
                hr(),
                h3("ChordPlot"),
                fluidRow(
                  column(
                    align = "center",
                    offset = 2,
                    chorddiagOutput("keggChordDown", width = "700px", height = "700px"),
                    width = 8
                  )),
                hr(),
                h3("DotPlot"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("keggDotDown"),
                    width = 8
                  )),
                hr(),
                h3("Heatmap"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("heatmapKeggDown"),
                    width = 8
                  )
                ),
                hr(),
                h3("NetPlot"),
                fluidRow(
                  class="text-center",
                  column(
                    align = "center",
                    offset= 2,
                    plotOutput("cnetKeggDown"),
                    width = 8
                  ))
              ) # fin tabpanel
            )),
    tabItem( tabName = "go", # GO tab GO tab
             tabsetPanel(
               tabPanel("All DE genes",
                        h3("Biological proccess"),
                        fluidRow(column(
                          # table BP
                          width = 8,
                          offset = 2,
                          dataTableOutput("tableBPall")
                        )),
                        hr(),
                        fluidRow(
                          #plot BP
                          class = "text-center",
                          column(
                            align = "center",
                            offset = 2,
                            plotlyOutput("plotBPall"),
                            width = 8)),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("BPDotall"),
                            width = 8)),
                        h3("Molecular Functions"),
                        fluidRow(column(
                          # table MF
                          width = 8,
                          offset = 2,
                          dataTableOutput("tableMFall")
                        )),
                        hr(),
                        fluidRow(# plot MF
                          class = "text-center",
                          column( align = "center",offset = 2,plotlyOutput("plotMFall"),width = 8)
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("MFDotall"),
                            width = 8
                          )
                        ),
                        h3("Cellular components"),
                        fluidRow( # table CC
                          column(width = 8,offset = 2,dataTableOutput("tableCCall"))
                        ),
                        hr(),
                        fluidRow(# plot CC
                          class = "text-center",
                          column(align = "center",offset = 2,plotlyOutput("plotCCall"),width = 8)
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("CCDotall"),
                            width = 8
                          )
                        ) #fin fluidrow
               ),
               tabPanel("Upregulated",
                        h3("Biological proccess"),
                        fluidRow(column(
                          # table BP
                          width = 8,
                          offset = 2,
                          dataTableOutput("tableBP")
                        )),
                        hr(),
                        fluidRow(
                          #plot BP
                          class = "text-center",
                          column(
                            align = "center",
                            offset = 2,
                            plotlyOutput("plotBP"),
                            width = 8)),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("BPDotUp"),
                            width = 8)),
                        h3("Molecular Functions"),
                        fluidRow(column(
                          # table MF
                          width = 8,
                          offset = 2,
                          dataTableOutput("tableMF")
                        )),
                        hr(),
                        fluidRow(# plot MF
                          class = "text-center",
                          column( align = "center",offset = 2,plotlyOutput("plotMF"),width = 8)
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("MFDotUp"),
                            width = 8
                          )
                        ),
                        h3("Cellular components"),
                        fluidRow( # table CC
                          column(width = 8,offset = 2,dataTableOutput("tableCC"))
                        ),
                        hr(),
                        fluidRow(# plot CC
                          class = "text-center",
                          column(align = "center",offset = 2,plotlyOutput("plotCC"),width = 8)
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("CCDotUp"),
                            width = 8
                          )
                        ) #fin fluidrow
               ),
               tabPanel("Downregulated",
                        h3("Biological proccess"),
                        fluidRow(column(# table BP
                          width = 8,
                          offset = 2,
                          dataTableOutput("tableBPdown")
                        )),
                        hr(),
                        fluidRow(#plot BP
                          class = "text-center",
                          column(
                            align = "center",
                            offset = 2,
                            plotlyOutput("plotBPdown"),
                            width = 8
                          )
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("BPDotDown"),
                            width = 8)),
                        h3("Molecular Functions"),
                        fluidRow(column(# table MF
                          width = 8,
                          offset = 2,
                          dataTableOutput("tableMFdown")
                        )),
                        hr(),
                        fluidRow(# plot MF
                          class = "text-center",
                          column( align = "center",offset = 2,plotlyOutput("plotMFdown"),width = 8)
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("MFDotDown"),
                            width = 8)),
                        h3("Cellular components"),
                        fluidRow( # table CC
                          column(width = 8,offset = 2,dataTableOutput("tableCCdown"))
                        ),
                        hr(),
                        fluidRow(# plot CC
                          class = "text-center",
                          column(align = "center",offset = 2,plotlyOutput("plotCCdown"),width = 8)
                        ),
                        hr(),
                        fluidRow(
                          class="text-center",
                          column(
                            align = "center",
                            offset= 2,
                            plotOutput("CCDotDown"),
                            width = 8)) #fin fluidrow
               ))), # tab GO
    tabItem(tabName = "gsea",
            h3("Gene Set Enrichment Analysis"),
            fluidRow(column(
              width = 8,
              offset = 2,
              dataTableOutput("gseaTable")
            )),
            hr(),
            fluidRow(column(
              width = 8,
              offset = 2,
              plotOutput("gseaPlot")
            ))
    ) #fin tab GSEA
  ) # fin tab items
)# fin dashboardbody

########################################## UI #################################################

ui <- dashboardPage(title="Rnaseq viewer and report",
                    header,
                    sidebar,
                    body
) # fin del UI

########################################## SERVER #################################################
server <- function(input, output, session) {
  
  observeEvent(input$aboutButton, {
    shinyalert("Enrich app 2020", "Authors:
            Miriam Riquelme Pérez (corresponding author)
            Fernando Pérez Sanz
            For any suggestion or bug, please contact us
            miriam.riquelmep@gmail.com",
               imageUrl = "dna-svg-small-13.gif", 
               imageWidth = 200, imageHeight = 100)})
  
  data <- reactiveValues() # genes
  goDT <- reactiveValues() #pretabla GO
  kgg <- reactiveValues() # enrich kegg
  go <- reactiveValues() # enrich GO
  kggDT <- reactiveValues() # pretabla kegg
  datos <- reactiveValues(dds=NULL) #objetos dds post DESeq()
  gsea <- reactiveValues() # objeto GSEA
  logfcRange <- reactiveValues() # min y max logfc
  res <- reactiveValues()
  
  observeEvent(input$deseqFile, {
      datos$dds <- readRDS(input$deseqFile$datapath)
  })
    
  observeEvent(datos$dds, {
    validate(need(datos$dds, ""))
    # if(!is(datos$dds, "DESeqDataSet") | !("results" %in% mcols(mcols(datos$dds))$type) ){
    #   shinyalert("File format error",
    #   "File must be a DESeqDataSet class object
    #   and you should have run DESeq()", type = "error")} 
      if(!is(datos$dds, "DESeqDataSet") | !("results" %in% mcols(mcols(datos$dds))$type) ){
          createAlert(session, "alert", "fileAlert",title = "Oops!!", 
          content = "File must be a DESeqDataSet class object
           and you should have run DESeq()", append=FALSE, style = "error")
      }
      else {
        res$sh <- as.data.frame(lfcShrink(datos$dds, coef=2, type="apeglm", res = results(datos$dds)))
        conversion <- geneIdConverter(rownames(res$sh), specie() )
        res$sh$baseMean <- round(res$sh$baseMean,4)
        res$sh$lfcSE <- round(res$sh$lfcSE,4)
        res$sh$log2FoldChange <- round(res$sh$log2FoldChange,4)
        res$sh <- cbind(`Description`=conversion$description, res$sh)
        res$sh <- cbind(`GeneName_Symbol`=conversion$consensus, res$sh)
        res$sh <-  res$sh %>% select(-c(pvalue))
        if(specie() == "Mm" ){spc = "Mus_musculus"}
        else {spc = "Homo_sapiens"}
        links = paste0("<a href='http://www.ensembl.org/",spc,",/Gene/Summary?db=core;g=",
                       rownames(res$sh),"' target='_blank'>",rownames(res$sh),"</a>")
        res$sh <- cbind(`GeneName_Ensembl`= links, res$sh)
        
        logfcRange$min <- min(res$sh$log2FoldChange)
        logfcRange$max <- max(res$sh$log2FoldChange)
        closeAlert(session, "fileAlert")
      }
  })
  
  observeEvent(input$runEnrich, {
    data$genesUp <- getSigUpregulated(res$sh, padj(), logfc()[2], specie() ) 
    data$genesDown <- getSigDownregulated(res$sh, padj(), logfc()[1], specie() ) 
    data$genesall <- rbind(data$genesUp, data$genesDown)
    
    kgg$all <- customKegg(data$genesall, species = specie() ) #"Mm"), species.KEGG = "mmu")
    kggDT$all <- kegg2DT(kgg$all, data$genesall)
    
    kgg$up <- customKegg(data$genesUp, species = specie() )#"Mm")#, species.KEGG = "mmu")
    kggDT$up <- kegg2DT(kgg$up, data$genesUp)
    
    
    kgg$down <- customKegg(data$genesDown, species = specie() )# "Mm")#, species.KEGG = "mmu")
    kggDT$down <- kegg2DT(kgg$down, data$genesDown)
    
    go$all <- customGO(data$genesall, species = "Mm")
    goDT$all <- go2DT(enrichdf = go$all, data = data$genesall )
    
    go$up <- customGO(data$genesUp, species = "Mm")
    goDT$up <- go2DT(enrichdf = go$up, data = data$genesUp )
    
    go$down <- customGO(data$genesDown, species = "Mm")
    goDT$down <- go2DT(enrichdf = go$down, data = data$genesDown )
    
  })
  # generate reactive variable ###################
  rowsAll <- reactive({input$tableAll_rows_selected})
  rowsUp <- reactive({input$table_rows_selected})
  rowsdown <- reactive({input$tableDown_rows_selected})
  
  bprowsall <- reactive({input$tableBPall_rows_selected}) 
  mfrowsall <- reactive({input$tableMFall_rows_selected})
  ccrowsall <- reactive({input$tableCCall_rows_selected})
  
  bprowsup <- reactive({input$tableBP_rows_selected})
  mfrowsup <- reactive({input$tableMF_rows_selected})
  ccrowsup <- reactive({input$tableCC_rows_selected})
  
  bprowsdown <- reactive({input$tableBPdown_rows_selected})
  mfrowsdown <- reactive({input$tableMFdown_rows_selected})
  ccrowsdown <- reactive({input$tableCCdown_rows_selected})
  
  variables <- reactive({input$variables})
  gsearow <- reactive({input$gseaTable_rows_selected})
  specie <- reactive({input$specie})
  padj <- reactive({input$padj})
  logfc <- reactive({input$logfc})
  specie <- reactive({input$specie})
  biologicalText <- reactive({input$biologicalText})
  explainPreview <- reactive({input$explainPreview})
  keggAllText <- reactive({input$keggAllText})
  specie <- reactive({input$specie})
  
  # InputFile
  output$deseqFile <- renderUI({
      validate(need(specie(), ""))
      fileInput("deseqFile",
          "Choose RDS with DESeq object",
          placeholder = "RDS DESeq",
          accept = ".Rds")
  })
  
  # ui selector sample groups ###################
  output$sampleGroup <- renderUI({
    validate(need(datos$dds, ""))
    nvars <- colData(datos$dds) %>% 
      as.data.frame() %>% 
      select(-c(sizeFactor,replaceable)) %>% 
      names()
    selectInput("variables", label="Select condition[s] to plot PCA",
                choices = nvars,
                multiple = TRUE)
  })
  
  # ui selector logfc #######################
  output$logfc <- renderUI({
    validate(need(datos$dds, ""))
    sliderInput("logfc", label = "Select logFC range to remove (keep tails)",
                min=round(logfcRange$min,3), max=round(logfcRange$max, 3),
                #value = c(round(logfcRange$min,3)+1,round(logfcRange$max,3)-1 ), step = 0.1 )
                value = c(-0.5,0.5), step = 0.1 )
  })
  
  # ui selector padj #############################
  output$padj <- renderUI({
    validate(need(datos$dds,""))
    sliderInput("padj", label = "Select p-adjusted threshold", min = 0, max=0.2, value=0.05, step = 0.005 )
  })
  # infoboxes
  output$allbox <- renderInfoBox({
      validate(need(res$sh, ""))
      numall <- nrow( res$sh[ ((res$sh$log2FoldChange >= logfc()[2] |
                                    res$sh$log2FoldChange< logfc()[1]) &
                                   res$sh$padj <= padj() ),] ) 
      infoBox("All DE genes", numall, icon = icon("arrows-alt-v"), color = "light-blue", fill = TRUE)
  })
  output$upbox <- renderInfoBox({
      validate(need(res$sh, ""))
      numup <- nrow( res$sh[(res$sh$log2FoldChange >= logfc()[2]) & (res$sh$padj <= padj()), ]) 
      infoBox("Up-regulated genes", numup, icon = icon("thumbs-up", lib = "glyphicon"), color = "light-blue", fill=TRUE)
  })
  output$downbox <- renderInfoBox({
      validate(need(res$sh, ""))
      numdown <- nrow( res$sh[(res$sh$log2FoldChange <= logfc()[1]) & (res$sh$padj <= padj()), ]) 
      infoBox("Down-regulated genes", numdown, icon = icon("thumbs-down", lib = "glyphicon"), color = "light-blue", fill=TRUE)
  })
  # preview samples ###################
  output$samples <- DT::renderDataTable(server = TRUE,{
    validate(need(datos$dds, "Load file to render table"))
    metadata <- as.data.frame(colData(datos$dds)) %>% select(-c(sizeFactor,replaceable))
    datatable( metadata, extensions = "Buttons",
               rownames=FALSE,
               filter = list(position="top", clear=FALSE),
               options = list(
                 columnDefs = list(list(orderable = TRUE,
                                        className = "details-control",
                                        targets = 1),
                                   list(className = "dt-right", targets = 1:(ncol(metadata)-1))
                 ),
                 dom = "Bfrtipl",
                 buttons = c("copy", "csv", "excel", "pdf", "print"),
                 list(pageLength = 10, white_space = "normal")
               )
    )
  })  
  # preview table ###################
  output$preview <- DT::renderDT(server=TRUE,{
    validate(need(datos$dds, "Load file to render table"))
    validate(need(res$sh, "Load file to render table"))
    res.sh <- res$sh
    res.sh <- res.sh[ ((res.sh$log2FoldChange >= logfc()[2] |
                          res.sh$log2FoldChange< logfc()[1]) &
                         res.sh$padj <= padj() ),]
    datatable( res.sh, extensions = "Buttons", escape = FALSE,
               rownames = FALSE,
               filter = list(position="top", clear=FALSE),
               options = list(
                 columnDefs = list(list(orderable = FALSE,
                                        className = "details-control",
                                        targets = 1),
                                   list(className = "dt-right", targets = 1:(ncol(res.sh)-1))
                 ),
                 rowCallback = JS(
                   "function(row, data) {",
                   "for (i = 6; i < 8; i++) {",
                   "if (data[i]>1000 | data[i]<1){",
                   "$('td:eq('+i+')', row).html(data[i].toExponential(3));",
                   "}",
                   "}",
                   "}"),
                 dom = "Bfrtipl",
                 buttons = c("copy", "csv", "excel", "pdf", "print"),
                 list(pageLength = 10, white_space = "normal")
               )
    )
  })
  # view pca plot data ###################
  output$pca <- renderPlot( {
    validate(need(datos$dds, "Load file and condition to render PCA"))
    validate(need(variables(),"Load condition to render PCA" ) )
    plotPCA(rlog(datos$dds), intgroup = variables() )+
      theme(plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm"))+
        scale_size_manual(values = 4) +
    theme(text = element_text(size=16))
  })
  # view Volcano plot data ###################
  output$volcano <- renderPlot( {
    validate(need(datos$dds, "Load file and condition to render Volcano"))
    validate(need(res$sh, "Load file to render table"))
    res$sh$GeneName_Symbol <- as.character(res$sh$GeneName_Symbol)
    CustomVolcano(res$sh, lab = res$sh$GeneName_Symbol, 
                  x = 'log2FoldChange',
                  y = 'padj',
                  pCutoff = padj(),
                  FCcutoffUP = logfc()[2],
                  FCcutoffDOWN = logfc()[1],
                  xlim = c(-8, 8)
                  )
  })
  # view MA plot data ###################
  output$MA <- renderPlot( {
    validate(need(datos$dds, ""))
    validate(need(res$sh, "Load file to render plot"))
    validate(need(logfc(), ""))
    MA(res$sh, main = expression("SOCS3" %->% "GFP"),
       fdr = padj(), fcDOWN = logfc()[1], fcUP = logfc()[2] , size = 0.3,
       palette = c("#B31B21", "#1465AC", "darkgray"),
       genenames = res$sh$GeneName_Symbol,
       legend = "top", top = 15, select.top.method = c('padj','fc'),
       font.label = c("plain", 12),
       font.legend = c("plain", 15),
       font.main = "plain",
       cex.axis = 1.1, cex.lab = 1.3,
       ggtheme = theme_classic()
    )
  })
  # KEGG table All #####################################
  output$tableAll <- DT::renderDT(server=TRUE,{
    validate(need(kgg$all, "Load file to render table"))
    datatable2(
      kggDT$all, 
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(pageLength = 10, white_space = "normal"))
  }) 
  # KEGG barplot All ################
  output$keggPlotAll <- renderPlotly ({
    validate(need(kgg$all, "Load file to render BarPlot"))
    rowsAll <- rowsAll()
    if(is.null( rowsAll )){ rowsAll <- c(1:10) }
    plotKeggAll(enrichdf = kgg$all[rowsAll,], nrows = length(rowsAll ),
                genesUp = data$genesUp, genesDown = data$genesDown)
  })
  # KEGG chordiag plot All ###############
  output$keggChordAll <- renderChorddiag({
    validate(need(kgg$all, "Load file to render ChordPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){rowsAll <- c(1:10)}
    chordPlot(kgg$all[rowsAll, ], nRows = length(rowsAll), orderby = "P.DE")
  })
  # KEGG dotplot All ################### 
  output$keggDotAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render dotPlot"))
    validate(need(rowsAll(), "Select the paths of interest to render DotPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){rowsAll <- c(1:20)}
    dotPlotkegg(kgg$all[rowsAll,], n = length(rowsAll))
  })
  # KEGG heatmap All #################
  output$heatmapKeggAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render Heatmap"))
    validate(need(rowsAll(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$all, ""))
    heatmapKegg(kggDT$all, rowsAll() ) 
  })
  # KEGG cnet All #################
  output$cnetKeggAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render Net Plot"))
    validate(need(rowsAll(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$all, rowsAll())
  })
  # KEGG table up#####################################
  output$table <- DT::renderDT(server=TRUE,{
    validate(need(kgg$up, "Load file to render table"))
    datatable2(
      kggDT$up,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(pageLength = 10, white_space = "normal"))
  }) 
  # KEGG barplot up################
  output$keggPlot <- renderPlotly ({
    validate(need(kgg$up, "Load file to render BarPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){rowsUp <- c(1:10)}
    plotKegg(enrichdf = kgg$up[rowsUp,], nrows = length(rowsUp))
  })
  # KEGG chordiag plot up ###############
  output$keggChord <- renderChorddiag({
    validate(need(kgg$up, "Load file to render ChordPlot"))
    rowsUp<- rowsUp()
    if(is.null(rowsUp)){rowsUp <- c(1:10)}
    chordPlot(kgg$up[rowsUp, ], nRows = length(rowsUp), orderby = "P.DE")
  })
  # KEGG dotplot UP ################### 
  output$keggDotUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render dotPlot"))
    validate(need(rowsUp(), "Select the paths of interest to render DotPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){rowsUp <- c(1:20)}
    dotPlotkegg(kgg$up[rowsUp,], n = length(rowsUp))
  })
  # KEGG heatmap Up #################
  output$heatmapKeggUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render Heatmap"))
    validate(need(rowsUp(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$up, ""))
    heatmapKegg(kggDT$up, rowsUp())
  })
  # KEGG cnet Up #################
  output$cnetKeggUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render Net Plot"))
    validate(need(rowsUp(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$up, rowsUp())
  })
  
  # KEGG table down #####################################
  output$tableDown <- DT::renderDT(server=TRUE,{
    validate(need(kgg$down, "Load file to render table"))
    datatable2(
      kggDT$down,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(pageLength = 10, white_space = "normal"))
  }) 
  # KEGG barplot down ################
  output$keggPlotDown <- renderPlotly ({
    validate(need(kgg$down, "Load file to render BarPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){rowsdown <- c(1:10)}
    plotKegg(enrichdf = kgg$down[rowsdown,], nrows = length(rowsdown))
  })
  # KEGG chordiag plot down ###############
  output$keggChordDown <- renderChorddiag({
    validate(need(kgg$down, "Load file to render ChordPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){rowsdown <- c(1:10)}
    chordPlot(kgg$down[rowsdown, ], nRows = length(rowsdown), orderby = "P.DE")
  })
  # KEGG dotplot Down ################### 
  output$keggDotDown <- renderPlot({
    validate(need(kgg$down, "Load file to render DotPlot"))
    validate(need(rowsdown(), "Select the paths of interest to render dotPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){rowsdown <- c(1:20)}
    dotPlotkegg(kgg$down[rowsdown,], n = length(rowsdown))
  })
  # KEGG heatmap Down #################
  output$heatmapKeggDown <- renderPlot({
    validate(need(kgg$down, "Load file to render Heatmap"))
    validate(need(rowsdown(), "Select the paths of interest to render Heatmap"))
    heatmapKegg(kggDT$down, rowsdown())
  })
  # KEGG cnet Down #################
  output$cnetKeggDown <- renderPlot({
    validate(need(kgg$down, "Load file to render NetPlot"))
    validate(need(rowsdown(), "Select the paths of interest to render NetPlot"))
    rowsdown <- rowsdown()
    customCnetKegg(kgg$down, rowsdown())
  })
  # GO table BP ALL #####################
  output$tableBPall <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$all, "Load file to render table"))
    goDT <- goDT$all 
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal")
    )
  })
  # GO plots BP all #####################
  output$plotBPall <- renderPlotly({
    validate(need(go$all, "Load file to render plot"))
    bprowsall <- bprowsall()
    if(is.null(bprowsall)){bprowsall <- c(1:10)}
    gosBP <- go$all[go$all$Ont=="BP",]
    plotGOAll(enrichdf = gosBP[bprowsall, ], nrows = length(bprowsall), ont="BP", 
              genesUp = data$genesUp, genesDown = data$genesDown)
  })
  # GO BP dotplot all ################### 
  output$BPDotall <- renderPlot({
    validate(need(go$all, "Load file to render dotPlot"))
    validate(need(bprowsall(), "Select the terms of interest to render DotPlot"))
    bprowsall <- bprowsall()
    if(is.null(bprowsall)){bprowsall <- c(1:20)}
    gosBP <- go$all[go$all$Ont=="BP",]
    dotPlotGO(gosBP[bprowsall,], n = length(bprowsall))
  })
  # GO table MF all #####################
  output$tableMFall <- DT::renderDataTable({
    validate(need(goDT$all, "Load file to render table"))
    goDT <- goDT$all
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal",
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF all  #####################
  output$plotMFall <- renderPlotly({
    validate(need(go$all, "Load file to render plot"))
    mfrowsall <- mfrowsall()
    if(is.null(mfrowsall)){mfrowsall <- c(1:10)}
    gosMF <- go$all[go$all$Ont=="MF",]
    plotGOAll(enrichdf = gosMF[mfrowsall, ], nrows = length(mfrowsall), ont = "MF",
              genesUp = data$genesUp, genesDown = data$genesDown)
  })
  # GO MF dotplot all ################### 
  output$MFDotall <- renderPlot({
    validate(need(go$all, "Load file to render dotPlot"))
    validate(need(mfrowsall(), "Select the terms of interest to render DotPlot"))
    mfrowsall <- mfrowsall()
    if(is.null(mfrowsall)){mfrowsall <- c(1:20)}
    gosMF <- go$all[go$all$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsall,], n = length(mfrowsall))
  })
  # GO table CC all #####################
  output$tableCCall <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$all, "Load file to render table"))
    goDT <- goDT$all
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal",
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC all #####################
  output$plotCCall <- renderPlotly({
    validate(need(go$all, "Load file to render plot"))
    ccrowsall <- ccrowsall()
    if(is.null(ccrowsall)){ccrowsall <- c(1:10)}
    gosCC <- go$all[go$all$Ont=="CC",]
    plotGOAll(enrichdf = gosCC[ccrowsall,], nrows = length(ccrowsall), ont="CC",
              genesUp = data$genesUp, genesDown = data$genesDown)
  })
  # GO CC dotplot all ################### 
  output$CCDotall <- renderPlot({
    validate(need(go$all, "Load file to render dotPlot"))
    validate(need(ccrowsall(), "Select the terms of interest to render DotPlot"))
    ccrowsall <- ccrowsall()
    if(is.null(ccrowsall)){ccrowsall <- c(1:20)}
    gosCC <- go$all[go$all$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsall,], n = length(ccrowsall))
  })
  
  # GO table BP UP#####################
  output$tableBP <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal")
    )
  })
  # GO plots BP UP #####################
  output$plotBP <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    bprowsup <- bprowsup()
    if(is.null(bprowsup)){bprowsup <- c(1:10)}
    gosBP <- go$up[go$up$Ont=="BP",]
    plotGO(enrichdf = gosBP[bprowsup, ], nrows = length(bprowsup), ont="BP")
  })
  # GO BP dotplot up ################### 
  output$BPDotUp <- renderPlot({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(bprowsup(), "Select the terms of interest to render DotPlot"))
    bprowsup <- bprowsup()
    if(is.null(bprowsup)){bprowsup <- c(1:20)}
    gosBP <- go$up[go$up$Ont=="BP",]
    dotPlotGO(gosBP[bprowsup,], n = length(bprowsup))
  })
  # GO table MF UP #####################
  output$tableMF <- DT::renderDataTable({
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal",
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF UP #####################
  output$plotMF <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    mfrowsup <- mfrowsup()
    if(is.null(mfrowsup)){mfrowsup <- c(1:10)}
    gosMF <- go$up[go$up$Ont=="MF",]
    plotGO(enrichdf = gosMF[mfrowsup, ], nrows = length(mfrowsup), ont = "MF")
  })
  # GO MF dotplot up ################### 
  output$MFDotUp <- renderPlot({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(mfrowsup(), "Select the terms of interest to render DotPlot"))
    mfrowsup <- mfrowsup()
    if(is.null(mfrowsup)){mfrowsup <- c(1:20)}
    gosMF <- go$up[go$up$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsup,], n = length(mfrowsup))
  })
  # GO table CC UP #####################
  output$tableCC <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal",
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC UP #####################
  output$plotCC <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    ccrowsup <- ccrowsup()
    if(is.null(ccrowsup)){ccrowsup <- c(1:10)}
    gosCC <- go$up[go$up$Ont=="CC",]
    plotGO(enrichdf = gosCC[ccrowsup,], nrows = length(ccrowsup), ont="CC")
  })
  # GO CC dotplot up ################### 
  output$CCDotUp <- renderPlot({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(ccrowsup(), "Select the terms of interest to render DotPlot"))
    ccrowsup <- ccrowsup()
    if(is.null(ccrowsup)){ccrowsup <- c(1:20)}
    gosCC <- go$up[go$up$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsup,], n = length(ccrowsup))
  })
  # GO table BP DOWN #####################
  output$tableBPdown <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$down, "Load file to render table"))
    goDT <- goDT$down
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal")
    )
  })
  # GO plots BP DOWN #####################
  output$plotBPdown <- renderPlotly({
    validate(need(go$down, "Load file to render plot"))
    bprowsdown <- bprowsdown()
    if(is.null(bprowsdown)){bprowsdown <- c(1:10)}
    gosBP <- go$down[go$down$Ont=="BP",]
    plotGO(enrichdf = gosBP[bprowsdown, ], nrows = length(bprowsdown), ont="BP")
  })
  # GO BP dotplot down ################### 
  output$BPDotDown <- renderPlot({
    validate(need(go$down, "Load file to render dotPlot"))
    validate(need(bprowsdown(), "Select the terms of interest to render DotPlot"))
    bprowsdown <- bprowsdown()
    if(is.null(bprowsdown)){bprowsdown <- c(1:20)}
    gosBP <- go$down[go$down$Ont=="BP",]
    dotPlotGO(gosBP[bprowsdown,], n = length(bprowsdown))
  })
  # GO table MF DOWN #####################
  output$tableMFdown <- DT::renderDataTable({
    validate(need(goDT$down, "Load file to render table"))
    goDT <- goDT$down
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal",
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF DOWN #####################
  output$plotMFdown <- renderPlotly({
    validate(need(go$down, "Load file to render plot"))
    mfrowsdown <- mfrowsdown()
    if(is.null(mfrowsdown)){mfrowsdown <- c(1:10)}
    gosMF <- go$down[go$down$Ont=="MF",]
    plotGO(enrichdf = gosMF[mfrowsdown, ], nrows = length(mfrowsdown), ont = "MF")
  })
  # GO MF dotplot down ################### 
  output$MFDotDown <- renderPlot({
    validate(need(go$down, "Load file to render dotPlot"))
    validate(need(mfrowsdown(), "Select the terms of interest to render DotPlot"))
    mfrowsdown <- mfrowsdown()
    if(is.null(mfrowsdown)){mfrowsdown <- c(1:20)}
    gosMF <- go$down[go$down$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsdown,], n = length(mfrowsdown))
  })
  # GO table CC DOWN #####################
  output$tableCCdown <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$down, "Load file to render table"))
    goDT <- goDT$down
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(pageLength = 10, white_space = "normal",
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC DOWN #####################
  output$plotCCdown <- renderPlotly({
    validate(need(go$down, "Load file to render plot"))
    ccrowsdown <- ccrowsdown()
    if(is.null(ccrowsdown)){ccrowsdown <- c(1:10)}
    gosCC <- go$down[go$down$Ont=="CC",]
    plotGO(enrichdf = gosCC[ccrowsdown,], nrows = length(ccrowsdown), ont="CC")
  })
  # GO CC dotplot down ################### 
  output$CCDotDown <- renderPlot({
    validate(need(go$down, "Load file to render dotPlot"))
    validate(need(ccrowsdown(), "Select the terms of interest to render DotPlot"))
    ccrowsdown <- ccrowsdown()
    if(is.null(ccrowsdown)){ccrowsdown <- c(1:20)}
    gosCC <- go$down[go$down$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsdown,], n = length(ccrowsdown))
  })
  # GSEA table ##########################
  output$gseaTable <- renderDataTable({
    validate(need(datos$dds, "Load file to render table"))
    gsea$gsea <- gseaKegg(datos$dds)
    mygsea <- gsea$gsea
    #saveRDS(mygsea, "tmpResources/gsea.Rds")
    table <- mygsea@result[mygsea@result$p.adjust<=0.05 ,2:9] %>% 
      mutate_at(vars(3:7), ~round(., 4))
    DT::datatable( table,
                   rownames=FALSE,
                   filter = list(position="top", clear=FALSE),
                   options = list(
                     columnDefs = list(list(orderable = FALSE,
                                            className = "details-control",
                                            targets = 1)
                     ),
                     dom = "Bfrtipl",
                     buttons = c("copy", "csv", "excel", "pdf", "print"),
                     list(pageLength = 10, white_space = "normal")
                   )
    )
  })
  # GSEA plot ##########################
  output$gseaPlot <- renderPlot({
    validate(need(gsea$gsea, "Load file to render table"))
    gseanr <- gsearow()
    if(is.null(gseanr)){gseanr <- c(1)}
    enrichplot::gseaplot2(gsea$gsea, geneSetID = gseanr, pvalue_table = TRUE, ES_geom = "line")
  })
  # author name ######################
  author <- reactive({input$author})
  # generate report #############################
  output$report <- renderUI({
    #validate(need(datos$dds, ""))
    downloadButton("report2", "Generate report")
    
  })
  output$pdf <- renderUI({
    #validate(need(datos$dds, ""))
    downloadButton("reportpdf", "Generate pdf report")
  })
  output$report2 <- downloadHandler(
    # For PDF output, change this to "report.pdf"
    filename = "report.html",
    content = function(file) {
      tempReport <- file.path(tempdir(), "flexReport.Rmd")
      file.copy("flexReport.Rmd", tempReport, overwrite = TRUE)
      file.copy("utils.R", file.path(tempdir(),"utils.R"), overwrite = TRUE)
      file.copy("tmpResources/", tempdir(), overwrite = TRUE, recursive = TRUE)
      file.copy("resources/dna-svg-small-13.gif",
                file.path(tempdir(), "tmpResources/dna-svg-small-13.gif"), overwrite = TRUE)
      #do.call(file.remove, list(list.files("tmpResources/", full.names = TRUE)))
      nrall <- rowsAll()
      nrup <- rowsUp()
      nrdown <- rowsdown()
      bpnrup <- bprowsup()
      mfnrup <- mfrowsup()
      ccnrup <- ccrowsup()
      bpnrdown <- bprowsdown()
      mfnrdown <- mfrowsdown()
      ccnrdown <- ccrowsdown()
      variablepca <- variables()
      gseanr <- gsearow()
      bpnrall <- bprowsall()
      mfnrall <- mfrowsall()
      ccnrall <- ccrowsall()
      if(is.null(gseanr)){gseanr <- c(1)}
      if(is.null(nrup)){ nrup <- ( if( dim(kggDT$up)[1]<10) 1:dim(kggDT$up)[1] else c(1:10) ) } 
      if(is.null(nrall)){ nrall <-  ( if( dim(kggDT$all)[1]<10) 1:dim(kggDT$all)[1] else c(1:10) ) }
      if(is.null(nrdown)){ nrdown <- ( if( dim(kggDT$down)[1]<10) 1:dim(kggDT$down)[1] else c(1:10) ) }
      
      if(is.null(ccnrup)){ ccnrup <- ( if (dim(goDT$up[goDT$up$Ont=="CC", ])[1]<10)
                                             1:dim(goDT$up[goDT$up$Ont=="CC", ])[1] else c(1:10) ) }
      if(is.null(mfnrup)){ mfnrup <- ( if (dim(goDT$up[goDT$up$Ont=="MF", ])[1]<10)
                                             1:dim(goDT$up[goDT$up$Ont=="MF", ])[1] else c(1:10) ) }
      if(is.null(bpnrup)){ bpnrup <- ( if (dim(goDT$up[goDT$up$Ont=="BP", ])[1]<10)
                                             1:dim(goDT$up[goDT$up$Ont=="BP", ])[1] else c(1:10) )}
      
      if(is.null(ccnrdown)){ccnrdown <- ( if (dim(goDT$down[goDT$down$Ont=="CC", ])[1]<10)
                                              1:dim(goDT$down[goDT$down$Ont=="CC", ])[1] else c(1:10) ) }
      if(is.null(mfnrdown)){mfnrdown <- ( if (dim(goDT$down[goDT$down$Ont=="MF", ])[1]<10)
                                              1:dim(goDT$down[goDT$down$Ont=="MF", ])[1] else c(1:10) ) }
      if(is.null(bpnrdown)){bpnrdown <- ( if (dim(goDT$down[goDT$down$Ont=="BP", ])[1]<10)
                                              1:dim(goDT$down[goDT$down$Ont=="BP", ])[1] else c(1:10) )}
      
      if(is.null(bpnrall)){bpnrall <- ( if (dim(goDT$all[goDT$all$Ont=="BP", ])[1]<10)
                                            1:dim(goDT$all[goDT$all$Ont=="BP", ])[1] else c(1:10)) }
      if(is.null(mfnrall)){mfnrall <- ( if (dim(goDT$all[goDT$all$Ont=="MF", ])[1]<10)
                                            1:dim(goDT$all[goDT$all$Ont=="MF", ])[1] else c(1:10)) }
      if(is.null(ccnrall)){ccnrall <- ( if (dim(goDT$all[goDT$all$Ont=="CC", ])[1]<10)
                                            1:dim(goDT$all[goDT$all$Ont=="CC", ])[1] else c(1:10))}
      
      if(is.null(variablepca)){variablepca=NULL}
      params <- list(nrup=nrup, nrdown=nrdown, bpnrup=bpnrup, bpnrdown=bpnrdown,
                     mfnrup=mfnrup, mfnrdown=mfnrdown, ccnrup=ccnrup, ccnrdown=ccnrdown,
                     variablepca=variablepca, tempdir =tempdir(),
                     gseanr=gseanr, author=author(), nrall = nrall,
                     bpnrall=bpnrall, mfnrall=mfnrall, ccnrall=ccnrall,
                     explainPreview=explainPreview(), biologicalText=biologicalText(),
                     keggAllText = keggAllText(), deseq = datos$dds, 
                     kggAll = kgg$all, kggUp = kgg$up, kggDown = kgg$down,
                     kggDTall = kggDT$all, kggDTup = kggDT$up, kggDTdown = kggDT$down,
                     goAll = go$all, goDTall = goDT$all, goUp=go$up, goDTup = goDT$up,
                     goDown = go$down, goDTdown = goDT$down, gsea = gsea$gsea)
      rmarkdown::render(
        tempReport,
        output_file = file,
        params = params,
        envir = new.env(parent = globalenv( ))
      )
    } )
  # output$reportpdf <- downloadHandler(
  #   # For PDF output, change this to "report.pdf"
  #   filename = "report.pdf",
  #   content = function(file) {
  #     tempReport <- file.path(tempdir(), "pdfReport.Rmd")
  #     file.copy("pdfReport.Rmd", tempReport, overwrite = TRUE)
  #     file.copy("utils.R", file.path(tempdir(),"utils.R"), overwrite = TRUE)
  #     file.copy("tmpResources/", tempdir(), overwrite = TRUE, recursive = TRUE)
  #     do.call(file.remove, list(list.files("tmpResources/", full.names = TRUE)))
  #     nrall <- rowsAll()
  #     nrup <- rowsUp()
  #     nrdown <- rowsdown()
  #     if(is.null(nrall)){nrall <- c(1:10)}
  #     if(is.null(nrup)){nrup <- c(1:10)}
  #     if(is.null(nrdown)){nrdown <- c(1:10)}
  #     bpnrall <- bprowsall()
  #     mfnrall <- mfrowsall()
  #     ccnrall <- ccrowsall()
  #     if(is.null(bpnrall)){bpnrall <- c(1:10)}
  #     if(is.null(mfnrall)){mfnrall <- c(1:10)}
  #     if(is.null(ccnrall)){ccnrall <- c(1:10)}
  #     bpnrup <- bprowsup()
  #     mfnrup <- mfrowsup()
  #     ccnrup <- ccrowsup()
  #     if(is.null(bpnrup)){bpnrup <- c(1:10)}
  #     if(is.null(mfnrup)){mfnrup <- c(1:10)}
  #     if(is.null(ccnrup)){ccnrup <- c(1:10)}
  #     bpnrdown <- bprowsdown()
  #     mfnrdown <- mfrowsdown()
  #     ccnrdown <- ccrowsdown()
  #     if(is.null(bpnrdown)){bpnrdown <- c(1:10)}
  #     if(is.null(mfnrdown)){mfnrdown <- c(1:10)}
  #     if(is.null(ccnrdown)){ccnrdown <- c(1:10)}
  #     variablepca <- variables()
  #     if(is.null(variablepca)){variablepca=NULL}
  #     gseanr <- gsearow()
  #     if(is.null(gseanr)){gseanr <- c(1)}
  #     params <- list(nrup=nrup, nrdown=nrdown, bpnrup=bpnrup, bpnrdown=bpnrdown,
  #                    mfnrup=mfnrup, mfnrdown=mfnrdown, ccnrup=ccnrup, ccnrdown=ccnrdown,
  #                    variablepca=variablepca, tempdir =tempdir(),
  #                    gseanr=gseanr, author=author(), nrall = nrall,
  #                    bpnrall=bpnrall, mfnrall=mfnrall, ccnrall=ccnrall)
  #     rmarkdown::render(
  #       tempReport,
  #       output_file = file,
  #       params = params,
  #       envir = new.env(parent = globalenv())
  #     )
  #   } )
}


shinyApp(ui, server)