---
title: "RNAseq viewer report"
author: "`r params$author`"
output: 
    flexdashboard::flex_dashboard:
        vertical_layout: scroll
        orientation: rows
params:
  nr: NA
  bpnr: NA
  ccnr: NA
  mfnr: NA
  nrdown: NA
  bpnrdown: NA
  mfnrdown: NA
  ccnrdown: NA
  variablepca: NA
  tempdir: NA
  gseanr: NA
  author: NA
---



```{r setup, echo=FALSE, include=FALSE, comment=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.width = 12)
setwd(params$tempdir)
library(shinydashboard)
library(limma)
library(tidyverse)
library(DT)
library(purrr)
library(plotly)
library(DESeq2)
library("ggraph")
library("igraph")
source("utils.R")
genesUp <- readRDS( "genesUp.Rds")
genesDown <- readRDS("genesDown.Rds")
kggUp <- readRDS( "kggUp.Rds")
kggDTup <- readRDS( "kggDTup.Rds")
goUp <- readRDS( "goUp.Rds")
goDTup <- readRDS( "goDTup.Rds")
kggDown <- readRDS( "kggDown.Rds")
kggDTdown <- readRDS( "kggDTdown.Rds")
goDown <- readRDS( "goDown.Rds")
goDTdown <- readRDS( "goDTdown.Rds")
dds <- readRDS("deseq.Rds")
gsea <- readRDS("gsea.Rds")
```

All together {data-navmenu="Kegg"}
=====================================

Row 
------------------------------------

### tabla

```{r echo=FALSE}
predata <- kegg2DT(kggUp[params$nr, ], genesUp, nrows = length(params$nr))
datatable2( predata,
            vars = c("genes"),
            escape = FALSE,
            opts = list(pageLength = 10, white_space = "normal"))
```

### Barplot

```{r  echo=FALSE}
plotKegg(enrichdf = kggUp[params$nr,], nrows = length(params$nr) ) 
```



Row
------------------------------------


### ChorPlot

```{r echo=FALSE, warning=FALSE}
chordPlot(kggUp[params$nr, ], nRows = length(params$nr), orderby = "P.DE")
```

### Dotplot

```{r}
dotPlotkegg(kggUp[params$nr,], n = length(params$nr))+
        theme(text = element_text(size=10))
```

Row
------------------------------------

### Kegg heatmap

```{r}
heatmapKegg(kggDTup, params$nr)
```

### Kegg cnetplot

```{r}
customCnetKegg(kggUp, params$nr)
```



Upregulated {data-navmenu="Kegg"}
=====================================  


Downregulated {data-navmenu="Kegg"}
=====================================

